'use client';

import { Activity, ArrowDownToLine, ArrowRight, BookOpen, Check, ClipboardCheck, Clock3, FolderKanban, Users } from 'lucide-react';
import { Competency, ExtensionGroup, formatDate, GroupEvaluation, groupEvaluationMean, Student, students } from '../data/demo';

const getMembers = (group:ExtensionGroup) => group.studentIds.map(id=>students.find(student=>student.id===id)).filter((student):student is Student=>Boolean(student));
const fmt=(value:number)=>value.toFixed(1).replace('.',',');

export function StudentGroupDashboard({group,evaluations,competencies,onStart,onHistory}:{group?:ExtensionGroup;evaluations:GroupEvaluation[];competencies:Competency[];onStart:()=>void;onHistory:()=>void}) {
  const latest=evaluations[0];
  return <>
    <div className="page-heading"><div><div className="eyebrow">PROJETO DE EXTENSÃO</div><h1>Olá, Ana <span className="wave">✳</span></h1><p>Acompanhe seu projeto e registre sua percepção sobre o trabalho do grupo.</p></div>{group&&<button className="button primary" onClick={onStart}><ClipboardCheck size={17}/> Avaliar meu grupo</button>}</div>
    {group?<><div className="group-hero card"><div className="group-hero-icon"><FolderKanban size={26}/></div><div><span>MEU GRUPO · {group.name.toUpperCase()}</span><h2>{group.project}</h2><p>{getMembers(group).length} integrantes · {group.classId}</p></div><div className="group-hero-members">{getMembers(group).map(member=><span key={member.id} title={member.name}>{member.name.split(' ').slice(0,2).map(part=>part[0]).join('')}</span>)}</div></div>
      <div className="metric-grid"><div className="metric card"><div className="metric-icon violet"><Activity size={20}/></div><p>Média do grupo</p><strong>{latest?fmt(groupEvaluationMean(latest))+'/5':'—'}</strong><small>na sua última avaliação</small></div><div className="metric card"><div className="metric-icon blue"><ClipboardCheck size={20}/></div><p>Avaliações enviadas</p><strong>{evaluations.length}</strong><small>sobre este projeto</small></div><div className="metric card"><div className="metric-icon peach"><Users size={20}/></div><p>Integrantes</p><strong>{getMembers(group).length}</strong><small>no grupo de extensão</small></div></div>
      <div className="two-column"><section className="card panel"><div className="panel-head"><div><h2>Como vejo meu grupo</h2><p>Notas da avaliação mais recente</p></div><button className="text-button" onClick={onHistory}>Ver histórico <ArrowRight size={16}/></button></div>{latest?<div className="bars">{competencies.slice(0,6).map(c=><div className="bar-row" key={c.id}><span>{c.name}</span><div className="score-track"><span style={{width:`${(latest.scores[c.id]||0)*20}%`}}/></div><strong>{latest.scores[c.id]||'—'}</strong></div>)}</div>:<div className="empty"><BookOpen size={25}/><h3>Seu primeiro registro começa aqui</h3><p>Avalie o trabalho do grupo para visualizar as competências.</p></div>}</section><section className="card panel next-step"><div className="panel-head"><div><h2>Trabalho em equipe</h2><p>Reflita sobre a experiência no projeto</p></div></div><div className="step-illustration"><div className="step-orbit"><Users size={37}/></div></div><h3>Como o grupo está evoluindo?</h3><p>Pense na colaboração, comunicação e organização da equipe durante o projeto de extensão.</p><button className="button primary full" onClick={onStart}>Avaliar meu grupo <ArrowRight size={17}/></button></section></div></>:<div className="card group-empty"><FolderKanban size={30}/><h2>Você ainda não está em um grupo</h2><p>O professor precisa incluir Ana em um grupo de projeto de extensão para que a avaliação fique disponível.</p></div>}
  </>;
}

export function GroupAssessment({group,competencies,draft,notes,onScore,onNotes,onSubmit}:{group?:ExtensionGroup;competencies:Competency[];draft:Record<string,number>;notes:string;onScore:(id:string,value:number)=>void;onNotes:(value:string)=>void;onSubmit:()=>void}) {
  const answered=competencies.filter(c=>draft[c.id]).length;
  if(!group) return <div className="card group-empty"><FolderKanban size={30}/><h2>Avaliação indisponível</h2><p>Ana precisa estar vinculada a um grupo. Crie ou edite um grupo no perfil do professor.</p></div>;
  return <><div className="page-heading"><div><div className="eyebrow">AUTOAVALIAÇÃO DO PROJETO DE EXTENSÃO</div><h1>Avaliar meu grupo</h1><p>Registre como você percebe o trabalho coletivo no projeto <strong>{group.project}</strong>.</p></div><span className="pill blue">{answered} de {competencies.length} respondidas</span></div><div className="group-context card"><div className="group-context-icon"><Users size={21}/></div><div><strong>{group.name}</strong><small>{group.project} · {getMembers(group).length} integrantes</small></div></div><div className="assessment-layout"><div className="assessment-list">{competencies.map((c,index)=><div className="card assessment-item" key={c.id}><div className="assessment-number">{String(index+1).padStart(2,'0')}</div><div className="assessment-content"><div className="assessment-title"><div><h3>{c.name}</h3><p>Como o grupo demonstrou esta competência? {c.description}</p></div><span className="pill">{c.category}</span></div><div className="scale" role="group" aria-label={`Nota do grupo em ${c.name}`}>{[1,2,3,4,5].map(value=><button key={value} type="button" className={draft[c.id]===value?'selected':''} onClick={()=>onScore(c.id,value)} aria-pressed={draft[c.id]===value}>{value}</button>)}</div><div className="scale-labels"><span>Precisamos desenvolver</span><span>Demonstramos bem</span></div></div></div>)}<div className="card notes-card"><label htmlFor="group-notes">O que funcionou e o que o grupo pode melhorar? (opcional)</label><textarea id="group-notes" rows={4} value={notes} onChange={event=>onNotes(event.target.value)} placeholder="Ex.: Nos comunicamos bem, mas podemos dividir melhor as tarefas."/></div></div><aside className="card assessment-aside"><div className="aside-icon"><ClipboardCheck size={24}/></div><h3>Sua avaliação do grupo</h3><p>As notas representam sua percepção do trabalho coletivo, não a nota individual dos colegas.</p><div className="progress-count"><strong>{competencies.length?Math.round(answered/competencies.length*100):0}%</strong><span>concluído</span></div><div className="score-track"><span style={{width:`${competencies.length?answered/competencies.length*100:0}%`}}/></div><div className="divider"/><button className="button primary full" onClick={onSubmit}>Enviar avaliação <Check size={17}/></button><small>O rascunho é salvo automaticamente neste navegador.</small></aside></div></>;
}

export function GroupHistory({groups,evaluations,onView,onExport,onStart}:{groups:ExtensionGroup[];evaluations:GroupEvaluation[];onView:(evaluation:GroupEvaluation)=>void;onExport:()=>void;onStart:()=>void}) {
  const latest=evaluations[0];
  return <><div className="page-heading"><div><div className="eyebrow">PROJETO DE EXTENSÃO</div><h1>Histórico do grupo</h1><p>Revise as avaliações que você enviou sobre seus projetos.</p></div><button className="button secondary" onClick={onExport}><ArrowDownToLine size={17}/> Exportar CSV</button></div><div className="metric-grid"><div className="metric card"><div className="metric-icon violet"><ClipboardCheck size={20}/></div><p>Avaliações enviadas</p><strong>{evaluations.length}</strong><small>sobre os grupos</small></div><div className="metric card"><div className="metric-icon blue"><Activity size={20}/></div><p>Média mais recente</p><strong>{latest?fmt(groupEvaluationMean(latest)):'—'}</strong><small>de 5 pontos</small></div><div className="metric card"><div className="metric-icon peach"><Clock3 size={20}/></div><p>Último registro</p><strong>{latest?formatDate(latest.date):'—'}</strong><small>avaliação do projeto</small></div></div><section className="card panel"><div className="panel-head"><div><h2>Linha do tempo</h2><p>Seus projetos de extensão</p></div></div>{evaluations.length?<div className="history-list">{evaluations.map(e=><div className="history-item" key={e.id}><div className="history-icon"><Users size={19}/></div><div><strong>Avaliação do grupo {groups.find(g=>g.id===e.groupId)?.name||'arquivado'}</strong><small>{formatDate(e.date)} · {Object.keys(e.scores).length} competências</small></div><div className="history-score">{fmt(groupEvaluationMean(e))}<span>/5</span></div><button className="button secondary compact" onClick={()=>onView(e)}>Ver detalhes</button></div>)}</div>:<div className="empty"><h3>Sem avaliações enviadas</h3><p>Seu primeiro registro sobre o projeto aparecerá aqui.</p><button className="button primary" onClick={onStart}>Avaliar grupo</button></div>}</section></>;
}

export function GroupReportPanel({groups,evaluations,classId,period,competency,onView}:{groups:ExtensionGroup[];evaluations:GroupEvaluation[];classId:string;period:string;competency:string;onView:(evaluation:GroupEvaluation)=>void}) {
  const filtered=evaluations.filter(e=>{const group=groups.find(g=>g.id===e.groupId);return group&&(classId==='all'||group.classId===classId)&&(period==='all'||e.date.slice(0,7)>=period)&&(competency==='all'||e.scores[competency]!==undefined);});
  const participatingGroups=groups.filter(g=>filtered.some(e=>e.groupId===g.id));
  return <section className="card panel group-report-panel"><div className="panel-head"><div><h2>Avaliações dos grupos de extensão</h2><p>{filtered.length} registros feitos pelos alunos · {participatingGroups.length} {participatingGroups.length===1?'grupo':'grupos'} no filtro</p></div></div>{filtered.length?<div className="group-report-list">{participatingGroups.map(group=>{const records=filtered.filter(e=>e.groupId===group.id);const average=records.reduce((sum,e)=>sum+(competency==='all'?groupEvaluationMean(e):e.scores[competency]),0)/records.length;return <div className="group-report-row" key={group.id}><span className="group-report-icon"><FolderKanban size={19}/></span><span className="group-report-title"><strong>{group.project}</strong><small>{group.name} · {group.classId} · {records.length} {records.length===1?'avaliação':'avaliações'}</small></span><span className="group-report-average">{average.toFixed(1).replace('.',',')}<small>/5</small></span><button className="button secondary compact" onClick={()=>onView(records[0])}>Ver recente</button></div>})}</div>:<div className="empty"><h3>Nenhuma avaliação de grupo neste filtro</h3><p>Os registros feitos pelos alunos sobre seus projetos aparecerão aqui.</p></div>}</section>;
}


