'use client';

import { useState } from 'react';
import { Activity, ArrowRight, BarChart3, BookOpen, Check, ChevronRight, ClipboardCheck, GraduationCap, HeartHandshake, Lightbulb, Menu, MousePointer2, ShieldCheck, Sparkles, Users, X } from 'lucide-react';
import { initialCompetencies, Role } from '../data/demo';

const profileCards: { id: Role; title: string; eyebrow: string; description: string; points: string[]; icon: typeof GraduationCap; className: string }[] = [
  { id: 'aluno', title: 'Aluno', eyebrow: 'TRABALHO EM EQUIPE', description: 'Avalie o trabalho do seu grupo no projeto de extensão e acompanhe a trajetória.', points: ['Avaliação do próprio grupo', 'Histórico do projeto', 'Mapa de competências'], icon: GraduationCap, className: 'student' },
  { id: 'professor', title: 'Professor', eyebrow: 'ACOMPANHAMENTO', description: 'Organize grupos, vincule projetos e acompanhe alunos e equipes.', points: ['Criação de grupos', 'Alunos por projeto', 'Relatórios da turma'], icon: BookOpen, className: 'teacher' },
  { id: 'coordenador', title: 'Coordenação', eyebrow: 'VISÃO DO CONJUNTO', description: 'Explore tendências dos projetos e configure os perfis da demonstração.', points: ['Indicadores gerais', 'Perfis e permissões', 'Gestão de competências'], icon: BarChart3, className: 'coordinator' },
];

const capabilityCards = [
  { icon: ClipboardCheck, number: '01', title: 'Avaliar o grupo', description: 'Cada aluno registra sua percepção sobre o trabalho coletivo em um projeto de extensão.' },
  { icon: Activity, number: '02', title: 'Organizar projetos', description: 'O professor cria grupos, define o nome do projeto e escolhe os estudantes participantes.' },
  { icon: BarChart3, number: '03', title: 'Enxergar o coletivo', description: 'Relatórios filtráveis conectam avaliações dos grupos, turmas e competências.' },
];

const groups = [
  { title: 'Olhar para si', description: 'Consciência e gestão pessoal', ids: ['autoconhecimento','autorregulacao','resiliencia','adaptabilidade'], color: 'violet' },
  { title: 'Conectar-se', description: 'Relações e trabalho em grupo', ids: ['empatia','comunicacao','conflitos','colaboracao'], color: 'coral' },
  { title: 'Agir e criar', description: 'Reflexão e iniciativa', ids: ['pensamento','criatividade','decisao','tempo'], color: 'teal' },
];

export default function LandingPage() {
  const [menuOpen, setMenuOpen] = useState(false);
  const closeMenu = () => setMenuOpen(false);
  return <div className="landing">
    <header className="lp-header"><div className="lp-container lp-header-inner"><a className="lp-logo" href="#inicio" aria-label="GPTICS, voltar ao início" onClick={closeMenu}><span className="lp-logo-mark"><Sparkles size={20}/></span><span>GPTICS<small>Competências em foco</small></span></a><nav className={`lp-nav ${menuOpen?'open':''}`} aria-label="Navegação da apresentação"><a href="#proposta" onClick={closeMenu}>A proposta</a><a href="#como-funciona" onClick={closeMenu}>Como funciona</a><a href="#competencias" onClick={closeMenu}>Competências</a><a href="#perfis" onClick={closeMenu}>Para quem</a><a className="lp-mobile-cta" href="/demo" onClick={closeMenu}>Explorar protótipo <ArrowRight size={16}/></a></nav><a className="lp-header-cta" href="/demo">Explorar protótipo <ArrowRight size={15}/></a><button className="lp-menu-button" type="button" onClick={()=>setMenuOpen(!menuOpen)} aria-label={menuOpen?'Fechar menu':'Abrir menu'} aria-expanded={menuOpen}>{menuOpen?<X size={23}/>:<Menu size={23}/>}</button></div></header>

    <main>
      <section className="lp-hero" id="inicio"><div className="lp-container lp-hero-grid"><div className="lp-hero-copy"><div className="lp-kicker"><span className="lp-kicker-dot"/> PROJETO DE INICIAÇÃO CIENTÍFICA</div><h1>Competências que vão <em>além da sala de aula.</em></h1><p>Uma proposta para acompanhar competências socioemocionais em projetos de extensão — conectando a avaliação dos grupos, o olhar docente e a visão da coordenação.</p><div className="lp-hero-actions"><a className="lp-button lp-button-primary" href="/demo">Conhecer a demonstração <ArrowRight size={17}/></a><a className="lp-button lp-button-ghost" href="#proposta">Entenda a proposta <ChevronRight size={17}/></a></div><div className="lp-hero-note"><span className="lp-note-avatars"><i>A</i><i>P</i><i>C</i></span><span>Uma experiência para <strong>alunos, professores e coordenação</strong></span></div></div><div className="lp-hero-art" aria-label="Prévia ilustrativa do painel de competências"><div className="lp-art-glow one"/><div className="lp-art-glow two"/><div className="lp-floating-card lp-float-top"><span className="lp-float-icon coral"><HeartHandshake size={19}/></span><span><strong>Desenvolvimento integral</strong><small>Mais que uma nota</small></span></div><div className="lp-preview"><div className="lp-preview-side"><span className="lp-preview-brand"><Sparkles size={16}/></span><span className="active"/><span/><span/><span/></div><div className="lp-preview-main"><div className="lp-preview-top"><span>Visão geral <ChevronRight size={11}/> Competências</span><span className="lp-preview-user">AS</span></div><div className="lp-preview-greeting"><small>PAINEL DO ALUNO</small><strong>Seu grupo em foco.</strong><span>Acompanhe o projeto e a equipe.</span></div><div className="lp-preview-stats"><div><small>Média do grupo</small><strong>3,8<span>/5</span></strong></div><div><small>Avaliações</small><strong>02</strong></div><div><small>Integrantes</small><strong>03</strong></div></div><div className="lp-preview-chart"><div className="lp-preview-chart-head"><strong>Mapa de competências</strong><span>Última avaliação</span></div>{[['Autoconhecimento','76%'],['Empatia','92%'],['Comunicação','81%'],['Colaboração','87%']].map(([name,width])=><div className="lp-preview-row" key={name}><span>{name}</span><i><b style={{width}}/></i></div>)}</div></div></div><div className="lp-floating-card lp-float-bottom"><span className="lp-float-icon green"><Check size={20}/></span><span><strong>Progresso acompanhado</strong><small>Reflexão em cada etapa</small></span></div></div></div><div className="lp-hero-bottom"><div className="lp-container"><span>UM PROTÓTIPO PARA EXPLORAR</span><span className="lp-bottom-line"/><span>12 COMPETÊNCIAS · 3 PERSPECTIVAS · 1 JORNADA</span></div></div></section>

      <section className="lp-section lp-proposal" id="proposta"><div className="lp-container lp-proposal-grid"><div><span className="lp-section-label">01 / A PROPOSTA</span><h2>O que acontece quando olhamos <em>além das notas?</em></h2></div><div className="lp-proposal-text"><p>Habilidades como empatia, colaboração e autorregulação fazem parte da formação, mas nem sempre têm espaço para ser observadas e discutidas.</p><p>O GPTICS propõe uma jornada de avaliação formativa em projetos de extensão: o aluno avalia o trabalho do seu grupo, o professor organiza as equipes e a coordenação visualiza tendências para apoiar o acompanhamento.</p><div className="lp-proposal-callout"><Lightbulb size={20}/><span><strong>Ideia central</strong>Transformar percepções em conversas mais conscientes sobre desenvolvimento.</span></div></div></div></section>

      <section className="lp-section lp-how" id="como-funciona"><div className="lp-container"><div className="lp-section-heading"><div><span className="lp-section-label">02 / COMO FUNCIONA</span><h2>Uma jornada simples.<br/><em>Um olhar mais completo.</em></h2></div><p>Três etapas conectam a experiência do grupo ao acompanhamento da turma.</p></div><div className="lp-capabilities">{capabilityCards.map(card=><article className="lp-capability" key={card.number}><span className="lp-capability-number">{card.number}</span><span className="lp-capability-icon"><card.icon size={25}/></span><h3>{card.title}</h3><p>{card.description}</p><span className="lp-capability-arrow"><ArrowRight size={17}/></span></article>)}</div><div className="lp-how-note"><ShieldCheck size={19}/><span>Esta é uma demonstração visual com dados fictícios. As respostas criadas ficam apenas neste navegador.</span></div></div></section>

      <section className="lp-section lp-competencies" id="competencias"><div className="lp-container"><div className="lp-section-heading"><div><span className="lp-section-label">03 / O QUE OBSERVAMOS</span><h2>12 competências.<br/><em>Muitas possibilidades de crescimento.</em></h2></div><p>O modelo reúne habilidades pessoais, relacionais e de organização em uma linguagem acessível.</p></div><div className="lp-competency-grid">{groups.map((group,index)=><article className={`lp-competency-group ${group.color}`} key={group.title}><div className="lp-group-heading"><span>0{index+1}</span><div><h3>{group.title}</h3><p>{group.description}</p></div></div><ul>{group.ids.map(id=><li key={id}><span className="lp-list-dot"/>{initialCompetencies.find(c=>c.id===id)?.name}</li>)}</ul></article>)}</div></div></section>

      <section className="lp-section lp-profiles" id="perfis"><div className="lp-container"><div className="lp-section-heading"><div><span className="lp-section-label">04 / PARA QUEM</span><h2>Cada pessoa vê o que <em>precisa ver.</em></h2></div><p>Explore o mesmo sistema por três perspectivas complementares.</p></div><div className="lp-profiles-grid">{profileCards.map(profile=><article className={`lp-profile ${profile.className}`} key={profile.id}><div className="lp-profile-icon"><profile.icon size={25}/></div><span className="lp-profile-eyebrow">{profile.eyebrow}</span><h3>{profile.title}</h3><p>{profile.description}</p><ul>{profile.points.map(point=><li key={point}><Check size={15}/>{point}</li>)}</ul><a href={`/demo?perfil=${profile.id}`}>Explorar como {profile.id==='coordenador'?'coordenação':profile.id} <ArrowRight size={16}/></a></article>)}</div></div></section>

      <section className="lp-closing"><div className="lp-container lp-closing-inner"><div><span className="lp-closing-label"><MousePointer2 size={16}/> EXPERIMENTE A IDEIA</span><h2>Veja a proposta<br/><em>ganhar forma.</em></h2><p>Navegue pelos três perfis, organize um projeto de extensão, avalie o grupo e acompanhe os resultados no protótipo interativo.</p><a className="lp-button lp-button-light" href="/demo">Abrir demonstração <ArrowRight size={17}/></a></div><div className="lp-closing-art"><span className="lp-closing-ring one"/><span className="lp-closing-ring two"/><span className="lp-closing-core"><Sparkles size={47}/></span><span className="lp-closing-chip left"><Users size={16}/> Pessoas</span><span className="lp-closing-chip right"><BarChart3 size={16}/> Aprendizagem</span></div></div></section>
    </main>

    <footer className="lp-footer"><div className="lp-container"><div className="lp-footer-top"><div><a className="lp-logo" href="#inicio"><span className="lp-logo-mark"><Sparkles size={19}/></span><span>GPTICS<small>Competências em foco</small></span></a><p>Uma proposta de iniciação científica para acompanhar competências socioemocionais em projetos de extensão.</p></div><div><strong>Navegue</strong><a href="#proposta">A proposta</a><a href="#como-funciona">Como funciona</a><a href="#competencias">Competências</a><a href="#perfis">Perfis</a></div><div><strong>Experimente</strong><a href="/demo?perfil=aluno">Visão do aluno</a><a href="/demo?perfil=professor">Visão do professor</a><a href="/demo?perfil=coordenador">Visão da coordenação</a></div></div><div className="lp-footer-bottom"><span>© {new Date().getFullYear()} GPTICS · Protótipo acadêmico</span><span>Projeto de iniciação científica · Universidade Tiradentes</span></div></div></footer>
  </div>;
}


