'use client';

import { useState } from 'react';
import { ArrowRight, Check, ChevronDown, FolderKanban, Pencil, Plus, Save, ShieldCheck, Trash2, Users, X } from 'lucide-react';
import { classes, DemoProfile, ExtensionGroup, formatDate, GroupEvaluation, groupEvaluationMean, permissionOptions, Permission, Role, rolePermissions, students } from '../data/demo';

const roleNames:Record<Role,string>={aluno:'Aluno',professor:'Professor',coordenador:'Coordenação'};
const initials=(name:string)=>name.split(' ').slice(0,2).map(p=>p[0]).join('').toUpperCase();

export function TeacherGroupsOverview({groups,onOpen}:{groups:ExtensionGroup[];onOpen:(classId:string)=>void}) {
  return <section className="teacher-group-overview"><div className="section-heading"><div><h2>Grupos de extensão</h2><p>Projetos e equipes de todas as suas turmas</p></div><button className="text-button" onClick={()=>onOpen(classes[0].id)}>Gerenciar grupos <ArrowRight size={16}/></button></div><div className="groups-overview-grid">{groups.map(group=><button className="card group-overview-card" key={group.id} onClick={()=>onOpen(group.classId)}><span className="group-overview-icon"><FolderKanban size={18}/></span><span><small>{group.name} · {group.classId}</small><strong>{group.project}</strong><em>{group.studentIds.length} {group.studentIds.length===1?'integrante':'integrantes'}</em></span><ArrowRight size={16}/></button>)}</div></section>;
}

export function GroupsPage({groups,evaluations,classId,onClassChange,onSave,onDelete}:{groups:ExtensionGroup[];evaluations:GroupEvaluation[];classId:string;onClassChange:(id:string)=>void;onSave:(group:ExtensionGroup)=>void;onDelete:(id:string)=>void}) {
  const [editing,setEditing]=useState<ExtensionGroup|null>(null);
  const [creating,setCreating]=useState(false);
  const [name,setName]=useState('');
  const [project,setProject]=useState('');
  const [formClass,setFormClass]=useState(classId);
  const [members,setMembers]=useState<string[]>([]);
  const [error,setError]=useState('');
  const open=(group?:ExtensionGroup)=>{setEditing(group||null);setCreating(true);setName(group?.name||'');setProject(group?.project||'');setFormClass(group?.classId||classId);setMembers(group?.studentIds||[]);setError('');};
  const close=()=>{setCreating(false);setEditing(null);setError('');};
  const save=()=>{
    if(!name.trim()||!project.trim()){setError('Informe o nome do grupo e o título do projeto.');return;}
    if(members.length<2){setError('Selecione pelo menos dois alunos para formar o grupo.');return;}
    const affected=groups.filter(group=>group.id!==editing?.id&&group.classId===formClass&&group.studentIds.some(id=>members.includes(id)));
    const incomplete=affected.find(group=>group.studentIds.filter(id=>!members.includes(id)).length===1);
    if(incomplete){setError(`A transferência deixaria o grupo ${incomplete.name} com apenas um integrante. Selecione os demais integrantes ou ajuste esse grupo primeiro.`);return;}
    const evaluatedEmpty=affected.find(group=>group.studentIds.every(id=>members.includes(id))&&evaluations.some(e=>e.groupId===group.id));
    if(evaluatedEmpty){setError(`O grupo ${evaluatedEmpty.name} já tem avaliações e não pode ficar sem integrantes.`);return;}
    onSave({id:editing?.id||`grupo-${crypto.randomUUID()}`,name:name.trim(),project:project.trim(),classId:formClass,studentIds:members});close();
  };
  const classGroups=groups.filter(g=>g.classId===classId);
  const unassigned=students.filter(s=>s.classId===classId&&!groups.some(g=>g.studentIds.includes(s.id))).length;
  return <><div className="page-heading"><div><div className="eyebrow">PROJETOS DE EXTENSÃO</div><h1>Grupos e projetos</h1><p>Organize equipes, vincule alunos e acompanhe as avaliações de cada projeto.</p></div><button className="button primary" onClick={()=>open()}><Plus size={17}/> Criar grupo</button></div>
    <div className="card filter-card"><div className="field"><label htmlFor="groups-class">Turma</label><div className="select-wrap"><select id="groups-class" value={classId} onChange={e=>onClassChange(e.target.value)}>{classes.map(c=><option key={c.id} value={c.id}>{c.name} · {c.id}</option>)}</select><ChevronDown size={17}/></div></div><div className="group-filter-summary"><strong>{classGroups.length} {classGroups.length===1?'grupo':'grupos'}</strong><span>{unassigned} alunos sem grupo nesta turma</span></div></div>
    {classGroups.length?<div className="groups-grid">{classGroups.map(group=>{const groupEvals=evaluations.filter(e=>e.groupId===group.id);const mostRecent=groupEvals[0];return <article className="card group-card" key={group.id}><div className="group-card-top"><div className="group-card-icon"><FolderKanban size={23}/></div><span className="pill blue">{group.classId}</span></div><small>GRUPO {group.name.toUpperCase()}</small><h2>{group.project}</h2><div className="group-members"><strong>Integrantes · {group.studentIds.length}</strong>{group.studentIds.map(id=>{const student=students.find(s=>s.id===id);return student?<div key={id}><span className="avatar tiny">{initials(student.name)}</span><span>{student.name}</span></div>:null})}</div><div className="group-card-foot"><span><b>{groupEvals.length}</b> {groupEvals.length===1?'avaliação':'avaliações'} do grupo{mostRecent?` · última em ${formatDate(mostRecent.date)}`:''}</span><strong>{mostRecent?`${groupEvaluationMean(mostRecent).toFixed(1).replace('.',',')}/5`:'—'}</strong></div><div className="card-actions"><button className="button secondary" onClick={()=>open(group)}><Pencil size={15}/> Editar grupo</button><button className="icon-button bordered danger-button" title={`Excluir ${group.name}`} onClick={()=>onDelete(group.id)}><Trash2 size={16}/></button></div></article>})}</div>:<div className="card group-empty"><FolderKanban size={30}/><h2>Nenhum grupo nesta turma</h2><p>Crie um grupo, informe o projeto de extensão e selecione os alunos participantes.</p><button className="button primary" onClick={()=>open()}>Criar grupo <ArrowRight size={16}/></button></div>}
    {creating&&<div className="modal-backdrop" onMouseDown={close}><div className="modal card group-modal" role="dialog" aria-modal="true" aria-label={editing?'Editar grupo':'Criar grupo'} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><div className="eyebrow">PROJETO DE EXTENSÃO</div><h2>{editing?'Editar grupo':'Novo grupo'}</h2><p>Defina o projeto e os estudantes que vão trabalhar juntos.</p></div><button className="icon-button" onClick={close} aria-label="Fechar"><X size={20}/></button></div><div className="field"><label htmlFor="group-name">Nome do grupo</label><input id="group-name" value={name} onChange={e=>setName(e.target.value)} maxLength={60} placeholder="Ex.: Conexão Digital"/></div><div className="field"><label htmlFor="group-project">Nome do projeto de extensão</label><input id="group-project" value={project} onChange={e=>setProject(e.target.value)} maxLength={120} placeholder="Ex.: Inclusão digital para idosos"/></div><div className="field"><label htmlFor="group-class">Turma</label><div className="select-wrap"><select id="group-class" value={formClass} onChange={e=>{setFormClass(e.target.value);setMembers([]);}}>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><ChevronDown size={17}/></div></div><div className="group-member-picker"><div className="picker-heading"><strong>Integrantes</strong><span>{members.length} selecionados · mínimo 2</span></div>{students.filter(s=>s.classId===formClass).map(student=>{const otherGroup=groups.find(g=>g.id!==editing?.id&&g.studentIds.includes(student.id));return <label className="member-option" key={student.id}><input type="checkbox" checked={members.includes(student.id)} onChange={e=>setMembers(previous=>e.target.checked?[...previous,student.id]:previous.filter(id=>id!==student.id))}/><span className="avatar tiny">{initials(student.name)}</span><span><strong>{student.name}</strong><small>{otherGroup?`Atualmente em ${otherGroup.name} · será transferido`:`Matrícula ${student.registration}`}</small></span></label>})}</div>{error&&<p className="form-error" role="alert">{error}</p>}<div className="modal-actions"><button className="button secondary" onClick={close}>Cancelar</button><button className="button primary" onClick={save}><Save size={16}/> Salvar grupo</button></div></div></div>}
  </>;
}

export function ProfilesPage({profiles,onSave,onDelete}:{profiles:DemoProfile[];onSave:(profile:DemoProfile)=>string|void;onDelete:(id:string)=>void}) {
  const [editing,setEditing]=useState<DemoProfile|null>(null);
  const [open,setOpen]=useState(false);
  const [name,setName]=useState('');
  const [identifier,setIdentifier]=useState('');
  const [role,setRole]=useState<Role>('aluno');
  const [permissions,setPermissions]=useState<Permission[]>(rolePermissions.aluno);
  const [error,setError]=useState('');
  const start=(profile?:DemoProfile)=>{setEditing(profile||null);setName(profile?.name||'');setIdentifier(profile?.identifier||'');setRole(profile?.role||'aluno');setPermissions(profile?.permissions||rolePermissions.aluno);setError('');setOpen(true);};
  const close=()=>{setOpen(false);setEditing(null);setError('');};
  const save=()=>{
    if(!name.trim()||!identifier.trim()){setError('Informe o nome e a matrícula ou código.');return;}
    if(!permissions.length){setError('Selecione pelo menos uma permissão.');return;}
    const result=onSave({id:editing?.id||`perfil-${crypto.randomUUID()}`,name:name.trim(),identifier:identifier.trim(),role,permissions});
    if(result){setError(result);return;}close();
  };
  return <><div className="page-heading"><div><div className="eyebrow">GESTÃO DE ACESSO · SIMULAÇÃO</div><h1>Perfis e permissões</h1><p>Cadastre pessoas e escolha o que cada perfil poderia acessar no sistema.</p></div><button className="button primary" onClick={()=>start()}><Plus size={17}/> Adicionar perfil</button></div><div className="card info-banner"><ShieldCheck size={20}/><span>As permissões são uma demonstração de configuração. Este protótipo não tem login nem bloqueio real de acesso.</span></div><div className="card panel"><div className="panel-head"><div><h2>Perfis cadastrados</h2><p>{profiles.length} registros nesta demonstração</p></div></div><div className="profile-list">{profiles.map(profile=><div className="profile-row" key={profile.id}><div className="avatar">{initials(profile.name)}</div><div className="profile-identity"><strong>{profile.name}</strong><small>{profile.identifier}</small></div><span className={`role-chip ${profile.role}`}>{roleNames[profile.role]}</span><div className="profile-permissions">{profile.permissions.map(id=><span key={id}>{permissionOptions.find(p=>p.id===id)?.label}</span>)}</div><div className="profile-actions"><button className="icon-button bordered" title={`Editar ${profile.name}`} onClick={()=>start(profile)}><Pencil size={16}/></button><button className="icon-button bordered danger-button" title={`Excluir ${profile.name}`} onClick={()=>onDelete(profile.id)}><Trash2 size={16}/></button></div></div>)}</div></div>
    {open&&<div className="modal-backdrop" onMouseDown={close}><div className="modal card profile-modal" role="dialog" aria-modal="true" aria-label={editing?'Editar perfil':'Adicionar perfil'} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><div className="eyebrow">PERFIL DEMONSTRATIVO</div><h2>{editing?'Editar perfil':'Adicionar perfil'}</h2><p>Escolha o papel e ajuste as permissões abaixo.</p></div><button className="icon-button" onClick={close} aria-label="Fechar"><X size={20}/></button></div><div className="field"><label htmlFor="profile-name">Nome</label><input id="profile-name" value={name} onChange={e=>setName(e.target.value)} maxLength={90} placeholder="Nome da pessoa"/></div><div className="field"><label htmlFor="profile-id">Matrícula ou código</label><input id="profile-id" value={identifier} onChange={e=>setIdentifier(e.target.value)} maxLength={40} placeholder="Ex.: 2026001 ou PROF002"/></div><div className="field"><label htmlFor="profile-role">Papel</label><div className="select-wrap"><select id="profile-role" value={role} onChange={e=>{const next=e.target.value as Role;setRole(next);setPermissions(rolePermissions[next]);}}><option value="aluno">Aluno</option><option value="professor">Professor</option><option value="coordenador">Coordenação</option></select><ChevronDown size={17}/></div></div><div className="group-member-picker"><div className="picker-heading"><strong>Permissões</strong><span>{permissions.length} selecionadas</span></div>{permissionOptions.map(permission=><label className="permission-option" key={permission.id}><input type="checkbox" checked={permissions.includes(permission.id)} onChange={e=>setPermissions(previous=>e.target.checked?[...previous,permission.id]:previous.filter(id=>id!==permission.id))}/><span><strong>{permission.label}</strong><small>{permission.description}</small></span>{permissions.includes(permission.id)&&<Check size={16}/>}</label>)}</div>{error&&<p className="form-error" role="alert">{error}</p>}<div className="modal-actions"><button className="button secondary" onClick={close}>Cancelar</button><button className="button primary" onClick={save}><Save size={16}/> Salvar perfil</button></div></div></div>}
  </>;
}

