'use client';

import { ArrowLeft, ArrowRight, Check, ClipboardCheck, UserRound, Users } from 'lucide-react';
import { Competency, ExtensionGroup, formatDate, MemberEvaluation, memberEvaluationMean, Student, students } from '../data/demo';
import { MemberDraft } from '../lib/storage';
import { useState } from 'react';

const membersOf = (group: ExtensionGroup) => group.studentIds.map(id => students.find(student => student.id === id)).filter((student): student is Student => Boolean(student));
const average = (evaluation: MemberEvaluation) => memberEvaluationMean(evaluation).toFixed(1).replace('.', ',');

export function MemberAssessment({group, evaluatorId, competencies, evaluations, drafts, onScore, onNotes, onSubmit}:{group?:ExtensionGroup;evaluatorId:string;competencies:Competency[];evaluations:MemberEvaluation[];drafts:Record<string,MemberDraft>;onScore:(studentId:string,competencyId:string,value:number)=>void;onNotes:(studentId:string,value:string)=>void;onSubmit:(studentId:string)=>boolean}) {
  const [selectedId,setSelectedId]=useState<string|null>(null);
  if(!group) return <div className="card group-empty"><Users size={30}/><h2>Avaliação indisponível</h2><p>O professor precisa incluir você em um grupo de extensão.</p></div>;
  const members=membersOf(group);
  const selected=members.find(member=>member.id===selectedId);
  const draft=selected ? drafts[`${group.id}:${selected.id}`] || {scores:{},notes:''} : {scores:{},notes:''};
  const latestFor=(id:string)=>evaluations.find(evaluation=>evaluation.groupId===group.id&&evaluation.evaluatorStudentId===evaluatorId&&evaluation.studentId===id);
  const finished=members.filter(member=>latestFor(member.id)).length;

  if(selected) {
    const answered=competencies.filter(competency=>draft.scores[competency.id]>=1).length;
    return <><div className="page-heading"><div><div className="eyebrow">{selected.id===evaluatorId?'AUTOAVALIAÇÃO INDIVIDUAL':'AVALIAÇÃO ENTRE INTEGRANTES'}</div><h1>Avaliar {selected.name.split(' ')[0]}</h1><p>{selected.id===evaluatorId?'Reflita sobre sua contribuição':'Avalie a contribuição deste colega'} no projeto <strong>{group.project}</strong>.</p></div><span className="pill blue">{answered} de {competencies.length} respondidas</span></div><button className="text-button member-back" onClick={()=>setSelectedId(null)}><ArrowLeft size={17}/> Voltar aos integrantes</button><div className="assessment-layout"><div className="assessment-list">{competencies.map((competency,index)=><div className="card assessment-item" key={competency.id}><div className="assessment-number">{String(index+1).padStart(2,'0')}</div><div className="assessment-content"><div className="assessment-title"><div><h3>{competency.name}</h3><p>{competency.description}</p></div><span className="pill">{competency.category}</span></div><div className="scale" role="group" aria-label={`Nota de ${selected.name} em ${competency.name}`}>{[1,2,3,4,5].map(value=><button key={value} type="button" className={draft.scores[competency.id]===value?'selected':''} onClick={()=>onScore(selected.id,competency.id,value)} aria-pressed={draft.scores[competency.id]===value}>{value}</button>)}</div><div className="scale-labels"><span>Precisa desenvolver</span><span>Demonstra bem</span></div></div></div>)}<div className="card notes-card"><label htmlFor="member-notes">Observações sobre {selected.name.split(' ')[0]} (opcional)</label><textarea id="member-notes" rows={4} value={draft.notes} onChange={event=>onNotes(selected.id,event.target.value)} placeholder="Descreva uma contribuição ou um ponto de melhoria."/></div></div><aside className="card assessment-aside"><div className="aside-icon"><UserRound size={24}/></div><h3>{selected.id===evaluatorId?'Sua autoavaliação':`Avaliação de ${selected.name.split(' ')[0]}`}</h3><p>Cada integrante recebe um registro individual da sua percepção.</p><div className="progress-count"><strong>{competencies.length?Math.round(answered/competencies.length*100):0}%</strong><span>concluído</span></div><div className="score-track"><span style={{width:`${competencies.length?answered/competencies.length*100:0}%`}}/></div><div className="divider"/><button className="button primary full" onClick={()=>{if(onSubmit(selected.id))setSelectedId(null);}}>Enviar avaliação <Check size={17}/></button><small>O rascunho é salvo neste navegador.</small></aside></div></>;
  }

  return <><div className="page-heading"><div><div className="eyebrow">PROJETO DE EXTENSÃO · {group.name.toUpperCase()}</div><h1>Avaliar integrantes</h1><p>Faça sua autoavaliação e avalie individualmente cada colega do grupo.</p></div><span className="pill blue">{finished} de {members.length} enviados</span></div><div className="group-context card"><div className="group-context-icon"><Users size={21}/></div><div><strong>{group.project}</strong><small>{members.length} integrantes, incluindo você</small></div></div><section className="card panel"><div className="panel-head"><div><h2>Pessoas do grupo</h2><p>Escolha uma pessoa para responder às {competencies.length} competências.</p></div></div><div className="member-roster">{members.map(member=>{const latest=latestFor(member.id);const memberDraft=drafts[`${group.id}:${member.id}`];const isSelf=member.id===evaluatorId;return <button type="button" className="member-roster-item" key={member.id} onClick={()=>setSelectedId(member.id)}><span className="avatar small">{member.name.split(' ').slice(0,2).map(part=>part[0]).join('')}</span><span className="member-roster-name"><strong>{member.name}</strong><small>{isSelf?'Sua autoavaliação':'Avaliação do colega'} · {latest?`enviada em ${formatDate(latest.date)}`:memberDraft?'rascunho em andamento':'pendente'}</small></span><span className={`pill ${latest?'green':memberDraft?'amber':'neutral'}`}>{latest?'Avaliado':memberDraft?'Rascunho':'Pendente'}</span><ArrowRight size={17}/></button>})}</div></section><div className="info-banner member-info"><ClipboardCheck size={19}/><span>As respostas são individuais. Você pode fazer uma nova avaliação de qualquer integrante para registrar a evolução do projeto.</span></div></>;
}

export function MemberHistoryPanel({evaluations,groups,onView,onStart}:{evaluations:MemberEvaluation[];groups:ExtensionGroup[];onView:(evaluation:MemberEvaluation)=>void;onStart:()=>void}) {
  return <section className="card panel member-history-panel"><div className="panel-head"><div><h2>Autoavaliação e colegas</h2><p>{evaluations.length} {evaluations.length===1?'registro individual enviado':'registros individuais enviados'}</p></div><button className="text-button" onClick={onStart}>Avaliar integrantes <ArrowRight size={16}/></button></div>{evaluations.length?<div className="history-list">{evaluations.map(evaluation=>{const target=students.find(student=>student.id===evaluation.studentId);return <div className="history-item" key={evaluation.id}><div className="history-icon"><UserRound size={19}/></div><div><strong>{evaluation.studentId===evaluation.evaluatorStudentId?'Minha autoavaliação':`Avaliação de ${target?.name||'integrante'}`}</strong><small>{groups.find(group=>group.id===evaluation.groupId)?.name||'Grupo arquivado'} · {formatDate(evaluation.date)}</small></div><div className="history-score">{average(evaluation)}<span>/5</span></div><button className="button secondary compact" onClick={()=>onView(evaluation)}>Ver detalhes</button></div>})}</div>:<div className="empty"><h3>Nenhum integrante avaliado</h3><p>Comece por você ou por um colega do projeto.</p><button className="button primary" onClick={onStart}>Avaliar integrantes</button></div>}</section>;
}

export function MemberReportPanel({groups,evaluations,classId,period,competency,onView}:{groups:ExtensionGroup[];evaluations:MemberEvaluation[];classId:string;period:string;competency:string;onView:(evaluation:MemberEvaluation)=>void}) {
  const filtered=evaluations.filter(evaluation=>{const group=groups.find(item=>item.id===evaluation.groupId);return group&&(classId==='all'||group.classId===classId)&&(period==='all'||evaluation.date.slice(0,7)>=period)&&(competency==='all'||evaluation.scores[competency]!==undefined);});
  return <section className="card panel member-history-panel"><div className="panel-head"><div><h2>Avaliações dos integrantes</h2><p>{filtered.length} registros individuais feitos pelos alunos, incluindo autoavaliações</p></div></div>{filtered.length?<div className="history-list">{filtered.slice(0,12).map(evaluation=>{const student=students.find(item=>item.id===evaluation.studentId);const group=groups.find(item=>item.id===evaluation.groupId);const score=competency==='all'?memberEvaluationMean(evaluation):evaluation.scores[competency];return <div className="history-item" key={evaluation.id}><div className="history-icon"><UserRound size={19}/></div><div><strong>{student?.name||'Integrante'}</strong><small>{group?.project||'Projeto'} · {evaluation.studentId===evaluation.evaluatorStudentId?'autoavaliação':'avaliação de colega'} · {formatDate(evaluation.date)}</small></div><div className="history-score">{score.toFixed(1).replace('.',',')}<span>/5</span></div><button className="button secondary compact" onClick={()=>onView(evaluation)}>Ver detalhes</button></div>})}</div>:<div className="empty"><h3>Nenhuma avaliação individual neste filtro</h3><p>As avaliações dos integrantes aparecerão aqui após o envio pelo aluno.</p></div>}</section>;
}
